### ISSUE TITLE
Hidden window

### ISSUE THREAD

**Issue by sertalpbilal** [Ali-Hasan-Khan/Scrape-Whoscored-Event-Data#1]
Hi Ali Hasan, thanks for the useful repository. I have noticed that you are hiding Chrome when `minimize_window` argument is passed. It might be easier to run Chrome in headless mode, so it stays invisible.

``` python
options = webdriver.ChromeOptions()
options.add_argument("--headless")
driver = webdriver.Chrome('chromedriver.exe', options=options)
```

If you are interested, I can send a pull request.

**Comment by Ali-Hasan-Khan** [comment]
Thank you. Actually, I have tried using this but unfortunately whoscored uses Imperva technology that can catch headless chrome and block your IP address quite easily.
