### ISSUE TITLE
WhoScored Issue?

### ISSUE THREAD

**Issue by catabush05** [Ali-Hasan-Khan/Scrape-Whoscored-Event-Data#3]
Hi Ali, I was working on a project using your scraper to get data from the Liga Profesional in Argentina via WhoScored and ran into a bit of an issue. It seems that when I enter:
```jupyter-notebook
match_urls = main.getMatchUrls(comp_urls=league_urls, competition='Liga Profesional', season='2023')
``` 
I get an empty list as a result. Previous seasons are working just fine for the ARG league, and I tried other leagues using the same setup and those worked as well. I had also previously tried accessing this data with soccerdata and ran into similar issues. Are you aware if this is an issue with WhoScored/if there is a workaround? Thank you!! I love the scraper!

**Comment by Ali-Hasan-Khan** [comment]
Hi, the issue is fixed you can check now and let me know if you face any problems!

**Comment by catabush05** [comment]
Thank you so much! It works great. I really appreciate it!
