### ISSUE TITLE
league_urls = main.getLeagueUrls() Issue

### ISSUE THREAD

**Issue by garyldavis** [Ali-Hasan-Khan/Scrape-Whoscored-Event-Data#4]
I came over this issue on 4/6/24 when trying to run the code.

[League URL Issue.txt](https://github.com/Ali-Hasan-Khan/Scrape-Whoscored-Event-Data/files/14894819/League.URL.Issue.txt)

I'd appreciate any guidance you can give me. They may have altered the HTML code, but I'm unsure.

**Comment by Ali-Hasan-Khan** [comment]
I have fixed this issue in the latest commit!
